remote_theme: andrewbanchich/forty-jekyll-theme
#theme: jekyll-theme-hacker
title: arizzo35's Homepage
description: A collection of things I've worked on and things I find interesting.
url: https://arizzo35.github.io
